### ISSUE TITLE
доброго времени суток! подскажите, в чем проблема? 

### ISSUE THREAD

**Issue by Vistajdm** [achechulin/loodsman#1]
Использую этот код как основу, но вызываю дополнительно открытие формы.Вызываю его в автооперации на событие Выполнено - до наступления. По нажатии завершить всплывает окно Лоцман для комментирования состояния задачи, по нажатию ОК состояние стадии на долю секунды состояние изменяется на Выполнено и затем обратно в состояние Выполняется и открывается моя форма. С чем может быть связана данная проблема ? Заранее благодарю за помощь!

// Функция для использования в автооперации Workflow с помощью ExecPluginFunction 
        [DllExport("WFProjectList", CallingConvention.StdCall)]
        public static Variant _wfProjectList(Variant wfo, IntPtr versionData, object[] userData)
        {
            if (!_initialized)
            {
                Initialize();
                _initialized = true;
            }
            try
            {
                if (wfo.vt != (ushort)VarEnum.VT_DISPATCH) 
                { 
                    throw new ArgumentException();
                }
                IWFBusinessLogic wf = (IWFBusinessLogic)Marshal.GetTypedObjectForIUnknown(wfo.data1, typeof(IWFBusinessLogic));
                PDMVersionData data = (PDMVersionData)Marshal.PtrToStructure(versionData, typeof(PDMVersionData));
                bool res = WFProjectList(wf, data, userData);
Form form = new Form();//вот здесь
form.Show();// и вызываю метод загрузки данных в форму из базы даных
form.Launch();
                return new Variant(res);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString(), PluginCaption, MessageBoxButtons.OK, MessageBoxIcon.Error);
                return new Variant(VarEnum.VT_NULL);
            }
        }

**Comment by achechulin** [comment]
Автооперация, которая "до наступления", должна вызывать SetResultOperation(True) чтобы процесс двигался дальше. Если вызовет SetResultOperation(False) то действие отменяется.

**Comment by Vistajdm** [comment]
Отлично, это помогло. Можете уточнить еще один момент, возможно ли поменять очередность вызова окон? Чтобы при нажатии "Завершить" сначала открывалась моя форма, а затем диалоговое окно лоцман для комментирования изменения состояния задания

**Comment by achechulin** [comment]
Здесь не подскажу. Можно попробовать вместо событие "Выполнено" использовать "Принято к исполнению".

**Comment by Vistajdm** [comment]
Здравствуйте еще раз, подскажите..
В коде автооперации MsgBox выводит пустое окно в независимости закрываю я его или нажимаю на кнопку Отправить, и при этом при вызове обработчика Выполнено до наступления всегда срабатывает SetResultOperation(true), хотя окно MsgBox пустое и должно сработать условие else SetResultOperation(false). Может я возвращают неправильное значение из метода ?
public static bool WFProjectList(IWFBusinessLogic wf, PDMVersionData versionData, object[] userData)
{
return true;
}

[DllExport("WFProjectList", CallingConvention.StdCall)]
public static Variant _wfProjectList(Variant wfo, IntPtr versionData, object[] userData)
{
if (!_initialized)
{
Initialize();
_initialized = true;
}
try
{
if (wfo.vt != (ushort)VarEnum.VT_DISPATCH)
{
throw new ArgumentException();
}
IWFBusinessLogic wf = (IWFBusinessLogic)Marshal.GetTypedObjectForIUnknown(wfo.data1, typeof(IWFBusinessLogic));
PDMVersionData data = (PDMVersionData)Marshal.PtrToStructure(versionData, typeof(PDMVersionData));
bool res = WFProjectList(wf, data, userData);
Int idBp = data.routeId;
Form form = new Form();//вот здесь
form.LaunchForm(idBp);
var dialogResult = form.ShowDialog();
If (dialogResult == DialogResult.OK)
 return new Variant(res);
else 
 return new Variant(VarEnum.VT_NULL)
}
catch (Exception ex)
{
MessageBox.Show(ex.ToString(), PluginCaption, MessageBoxButtons.OK, MessageBoxIcon.Error);
return new Variant(VarEnum.VT_NULL);
}
}
Код автооперации: 
begin 
stResult:= ExecPluginFunction('myDll.dll', 'WFProjectList', null);
MsgBox('', stResult, MB_OK);
If stResult <> ''
 SetResultOperation(true) 
Else 
SetResultOperation(false) 
End;
